
project_id = "corrklfwxfuqusfzwbls"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://localhost:8080"
additional_redirect_urls = ["https://localhost:8080"]
jwt_expiry = 3600
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[edge_runtime]
enabled = true
policy = "per_worker"

[functions.process-payment]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.process-payment-v2]
verify_jwt = false

[functions.process-payment-debug]
verify_jwt = false
